version: '3.9'

services:
  # PHP + Apache Service
  app:
    image: rabinmaharjan07/php-hello-world  # Pulls the php-hello-world image from your Docker Hub repository
    container_name: intuji-devops-php-apache  # Name of the container
    ports:
      - "8088:80"  # Map port 8088 on the host to port 80 on the container
    volumes:
      - .:/var/www/html # Mount the current directory into the container for live updates
    networks:
      - app-network
    environment:
      - TZ=Asia/Kathmandu  # Set the timezone to Nepal Time (although the container already sets it)
  
# Networks
networks:
  app-network:
    driver: bridge
