version: '3.9'

services:
  # PHP + Apache Service
  app:
    build:
      context: .  # Build from the current directory where your Dockerfile is located
    container_name: php-apache-app
    ports:
      - "8088:80"  # Map port 8082 on the host to port 80 on the container
    volumes:
      - .:/var/www/html  # Mount the current directory into the container for live updates
    networks:
      - app-network
    environment:
      - TZ=Asia/Kathmandu  # Set the timezone to Nepal Time

# Networks
networks:
  app-network:
    driver: bridge

