name: PHP CI/CD Action

inputs:
  docker-compose-file:
    description: 'Path to the docker-compose.yml file'
    required: true
    default: 'docker-compose.yml'

  deploy:
    description: 'Whether to deploy the application'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Build the Docker image
    - name: Build Docker image
      run: docker-compose -f ${{ inputs.docker-compose-file }} build

    # Run tests
    - name: Run tests
      run: docker-compose -f ${{ inputs.docker-compose-file }} run --rm app php ./vendor/bin/phpunit tests

    # Deploy the application (if enabled)
    - name: Start application
      if: ${{ inputs.deploy == 'true' }}
      run: docker-compose up -d
