name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  php-cicd:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build

      # Step 4: Run tests using PHPUnit
      - name: Run tests
        run: docker-compose -f docker-compose.yml run --rm app php ./vendor/bin/phpunit tests

      # Step 5 (Optional): Start the application
      - name: Start application
        if: github.ref == 'refs/heads/main'
        run: docker-compose up -d
