name: CI/CD Workflow

on:
  push:
    branches:
      - master
  

jobs:
  php-cicd:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build

      # Step 4: Run tests using PHPUnit
      - name: Run tests
        run: docker-compose -f docker-compose.yml run --rm app php ./vendor/bin/phpunit tests

      # Step 5 (Optional): Start the application
      - name: Start application
        if: github.ref == 'refs/heads/master'
        run: docker-compose up -d
